 # This is a basic workflow to help you get started with Actions

name: Deploy to EC2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    
    # checkout master repo
    - name: checkout
      uses: actions/checkout@master
    
    - name: Deploy to WebServer
      uses: appleboy/ssh-action@master
      env:
        USERNAME: ubuntu
        HOST: ${{ secrets.KNOWN_HOSTS }} 
        KEY: ${{ secrets.SSH_KEY }}
    - name: rsync over ssh
      run: rsync ./ ubuntu@${{ secrets.KNOWN_HOSTS }}:/home/ubuntu/collab
