# Generated by Django 3.1 on 2020-09-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200904_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='Student', max_length=20),
        ),
    ]
